#included: # paths to include during linting. `--path` is ignored if present
#  - Shared

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - fastlane
  - .build # Where Swift Package Manager checks out dependency sources
  - SourcePackages
  - ../../Shared/Legacy

analyzer_rules:
  - unused_declaration
  - unused_import

opt_in_rules:
  - force_unwrapping
  - number_separator

disabled_rules: # rule identifiers to exclude from running
#  - multiple_closures_with_trailing_closure
#  - colon
#  - comma
#  - control_statement
  - trailing_whitespace
  - identifier_name
  
identifier_name:
  excluded:
    - id
number_separator:
  minimum_length: 5

file_length:
  warning: 500
  error: 1200

force_unwrapping:
  severity: error
force_cast:
  severity: error
force_try:
  severity: error

line_length:
  warning: 120
  ignores_comments: true
  
nesting:
  type_level:
    warning: 3 ## This means the warning appears if you nest 3 level deep instead of 1
    error: 5
  function_level:
    warning: 4
    error: 10

reporter: "xcode"
